version: 1.0.{build}

image: Visual Studio 2019

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    platform: x64
    qt: 5.14.2    
    release_name: simple-image-processer-vs2019-x64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    platform: x86
    qt: 5.14.2
    release_name: simple-imgae-processer-vs2019-x86

before_build:
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" set msvc=msvc2017
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" set vs=C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build
  - if "%platform%"=="x86" set QTDIR=C:\Qt\%qt%\msvc2017
  - if "%platform%"=="x64" set QTDIR=C:\Qt\%qt%\msvc2017_64
  - set PATH=%PATH%;%QTDIR%\bin;C:MinGW\bin;
  - if "%platform%"=="x86" set vcvars=%vs%\vcvars32.bat
  - if "%platform%"=="x64" set vcvars=%vs%\vcvars64.bat

build_script:
  - call "%vcvars%"
  - cmake -B ./build .
  - cd build
  - msbuild ./image-processer.sln
  - cd ..
