version: 1.0.{build}

image: Visual Studio 2019

environment:
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    platform: x64
    qt: 5.14.2    
    release_name: simple-image-processer-vs2019-x64
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    platform: x86
    qt: 5.14.2
    release_name: simple-imgae-processer-vs2019-x86

before_build:
  - if "%platform%"=="x86" set QTDIR=C:/Qt/%qt%/mingw73_32
  - if "%platform%"=="x64" set QTDIR=C:/Qt/%qt%/mingw73_64
  - if "%platform%"=="x86" set QTTOOLS=C:/Qt/Tools/mingw730_32
  - if "%platform%"=="x64" set QTTOOLS=C:/Qt/Tools/mingw730_64
  - set PATH=%PATH%;%QTDIR%/bin;%QTTOOLS%/bin;
  - if "%platform%"=="x86" set vcvars=%vs%/vcvars32.bat
  - if "%platform%"=="x64" set vcvars=%vs%/vcvars64.bat

build_script:
  - cmake -DCMAKE_C_COMPILER=gcc.exe -DCMAKE_CXX_COMPILER=g++.exe -DCMAKE_BUILD_TYPE=Release -G "MinGW Makefiles" -B ./build .
  - cd build
  - mingw32-make
  - mkdir release
  - cp ./src/image-processer.exe ./release
  - windeployqt --qmldir %QTDIR%/qml ./release/image-processer.exe
  - cd ..

artifacts:
  - path: ./build/release
    name: $(release_name)

deploy:
  provider: GitHub
  auth_token:
    secure: BpBlm35pE+T35mcffyNCOZH8fRik/UIBHy/FgB+mR1xSldsB/mc89NNj8vt83kMD
  description: "simple-image-processer"
  draft: true
  prerelease: false
  on:
    branch: master
    APPVEYOR_REPO_TAG: true